package main

var levels = map[string][]string{
	"newbieland": {
		"                                                                                                                     000000000000000",
		"                                                                                                                     0             0",
		"                                                                                                                     0          7  0",
		"                                                                                                                     0             0",
		"                                                                                                   000000000000000   0             0",
		"                                                                                                                     066666000000000",
		"                                                                                  000000000000000                                  0",
		"                                                                                                                                   0",
		"                                                                            000000                                                 0",
		"                                                                                                                   00000000000000000",
		"  1234                       0 0                                                                                                    ",
		"                            00 00                                                                                                   ",
		"0000000000000000000000000000000000                                                                                                  ",
		"                                  000                                                                                               ",
		"                                    0                                                                                               ",
		"                                             5                                                                                      ",
		"                                                                                                                                    ",
		"                                                             000000000000000                                                        ",
		"                                     000000000000000000000000                                                                       ",
	},
	"buto":     {},
	"pyramids": {},
	"robocity": {
		"1234                                    ",
		"AAAAD                                   ",
		"                                        ",
		"                                        ",
		"                                        ",
		"                                        ",
		"                                        ",
		"CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC  A",
		"A                      5               A",
		"A                                      A",
		"A                                      A",
		"A                                      A",
		"A                      BBBBBBBBBBBBBBBBA",
		"A                      A               A",
		"A                      A               A",
		"A                      A               A",
		"A                      A               A",
		"A                      A               A",
		"A  BBBBBBDBBBBDBBBBBBBBA               A",
		"A                                      A",
		"A                                 B A  A",
		"A                            A B    A  A",
		"A                         A  A      A  A",
		"A                      A  A  A      A  A",
		"ACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC  A",
		"A                                  5   A",
		"A                                      A",
		"A                                      A",
		"A                                      A",
		"A                                  A   A",
		"A 7                                A   A",
		"A         A    A                   A   A",
		"A        AA    AA          A       A   A",
		"ACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCA",
	},
	"assembly":     {},
	"infernal hop": {},
	"going down":   {},
	"slip":         {},
}
